import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import FooterCopyright from "@/components/FooterCopyright";

const open_Sans = Open_Sans({
  weight: [ "300" , "400" , "500" , "700"],
  style: ["normal","italic"],
  subsets: ["cyrillic"]

})

export const metadata: Metadata = {
  title: "White Liner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      className={open_Sans.className}
      lang="en"
      >
      <body>
        <div>
          <Header />
        </div>
          {children}
        <div>
          <Footer />
        </div>
        <FooterCopyright />

      </body>
    </html>
  );
}
